import { FC } from "react"
import Head          from 'next/head'
import Header from '../Header/Header'
import Footer from '../Footer/Footer'

import { Poppins }     from '@next/font/google'
import { LayoutProps } from './LayoutProps'

const poppins = Poppins({
	weight: ['400', '700'],
	style: 'normal',
	subsets: ['latin'],
})

const Layout:FC<LayoutProps> = ({children}) => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico"/>
				<noscript id="inject-styles-here"></noscript>
			</Head>

			<div className={`min-h-screen flex flex-col ${poppins.className}`}>
				<Header/>

				<main className="flex-grow">
					{children}
				</main>

				<Footer/>
			</div>
		</>
	)
}

export default Layout